### ISSUE TITLE
Crash report after optimization of GrapheneOS

### ISSUE THREAD

**Issue by JanWaldhorn** [sommd/auto-mute#12]
I use GrapheneOS on my Pixel 6.
After each system update, the apps are optimized in the background (ahead-of-time compilation, more [here](https://discuss.grapheneos.org/d/2684-optimizing-apps-during-update-takes-very-long-time)). Afterwards the optimized apps have to be restarted. This works without problems for all apps, only from Automute I get an error message like "App closed repeatedly". Here is an excerpt from the log file:

```
type: crash
osVersion: google/oriole/oriole:14/AP2A.240805.005.F1/2024080600:user/release-keys
package: xyz.sommd.automute:105002000
process: xyz.sommd.automute
processUptime: 169 + 812 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to create service xyz.sommd.automute.service.AutoMuteService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service xyz.sommd.automute/.service.AutoMuteService
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4942)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2414)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service xyz.sommd.automute/.service.AutoMuteService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5036)
	at android.os.Parcel.readParcelable(Parcel.java:5018)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3187)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6975)
	at android.app.Service.startForeground(Service.java:778)
	at xyz.sommd.automute.service.AutoMuteService.onCreate(SourceFile:12)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4929)
	... 11 more
```

**Comment by JanWaldhorn** [comment]
This error remains in the current release 1.5.1

```
type: crash
osVersion: google/oriole/oriole:15/AP4A.241205.013/2024120700:user/release-keys
package: xyz.sommd.automute:105012000, targetSdk 33
process: xyz.sommd.automute
processUptime: 336 + 399 ms
installer: com.machiav3lli.fdroid

java.lang.RuntimeException: Unable to create service xyz.sommd.automute.service.AutoMuteService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service xyz.sommd.automute/.service.AutoMuteService
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5093)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service xyz.sommd.automute/.service.AutoMuteService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5084)
	at android.os.Parcel.readParcelable(Parcel.java:5066)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3235)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
	at android.app.Service.startForeground(Service.java:778)
	at xyz.sommd.automute.service.AutoMuteService.onCreate(Unknown Source:302)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5080)
	... 11 more
```

**Comment by toast-riot** [comment]
Strange... I'm on GrapheneOS 2026030700, Pixel 9a, and have not encountered this issue. I've been using Auto Mute for a while, perhaps half a year.

**Comment by sommd** [comment]
I tested this with the latest GrapheneOS on a Pixel 6 and can't reproduce it. It seems like this was an issue with GrapheneOS that's since been fixed.
